export const PARKS_TABLE_ROWS = [
    {
        locator_number: 232612,
        park_name: "Admiral William Standley State Recreation Area",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.6462166,
        longitude: -123.6182765
    },
    {
        locator_number: 232613,
        park_name: "Ahjumawi Lava Springs State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 41.12497870000001,
        longitude: -121.4372694
    },
    {
        locator_number: 232614,
        park_name: "Albany State Marine Reserve",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.8882764,
        longitude: -122.3153517
    },
    {
        locator_number: 232615,
        park_name: "Anderson Marsh State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.92040970000001,
        longitude: -122.6134692
    },
    {
        locator_number: 232616,
        park_name: "Andrew Molera State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.2884177,
        longitude: -121.8442571
    },
    {
        locator_number: 232617,
        park_name: "Angel Island State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.8636084,
        longitude: -122.4319496
    },
    {
        locator_number: 232618,
        park_name: "Año Nuevo State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.1193293,
        longitude: -122.3075945
    },
    {
        locator_number: 232619,
        park_name: "Antelope Valley California Poppy State Natural Reserve",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.7249116,
        longitude: -118.3969062
    },
    {
        locator_number: 232620,
        park_name: "Antelope Valley Indian Museum State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.649594,
        longitude: -117.847417
    },
    {
        locator_number: 232621,
        park_name: "Anza-Borrego Desert State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.10049199999999,
        longitude: -116.3013266
    },
    {
        locator_number: 232622,
        park_name: "Armstrong Redwoods State Natural Reserve",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5370031,
        longitude: -123.0063252
    },
    {
        locator_number: 232623,
        park_name: "Arthur B. Ripley Desert Woodland State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: false,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.7534026,
        longitude: -118.4930856
    },
    {
        locator_number: 232624,
        park_name: "Asilomar State Beach",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.6180088,
        longitude: -121.9419115
    },
    {
        locator_number: 232625,
        park_name: "Auburn State Recreation Area",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.9037201,
        longitude: -121.0556301
    },
    {
        locator_number: 232626,
        park_name: "Austin Creek State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5592918,
        longitude: -123.0108184
    },
    {
        locator_number: 232627,
        park_name: "Azalea State Natural Reserve",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.9176332,
        longitude: -124.0793029
    },
    {
        locator_number: 232628,
        park_name: "Bale Grist Mill State Historic Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5411943,
        longitude: -122.5088942
    },
    {
        locator_number: 232629,
        park_name: "Bean Hollow State Beach",
        dog_on_road: null,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.2273608,
        longitude: -122.4109773
    },
    {
        locator_number: 232630,
        park_name: "Benbow State Recreation Area",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.0675526,
        longitude: -123.7909954
    },
    {
        locator_number: 232631,
        park_name: "Benicia Capitol State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.05005390000001,
        longitude: -122.1588656
    },
    {
        locator_number: 232632,
        park_name: "Benicia State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.0733219,
        longitude: -122.192645
    },
    {
        locator_number: 232633,
        park_name: "Bethany Reservoir State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.7829387,
        longitude: -121.617005
    },
    {
        locator_number: 232634,
        park_name: "Bidwell Mansion State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 39.7323566,
        longitude: -121.8435715
    },
    {
        locator_number: 232635,
        park_name: "Bidwell-Sacramento River State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.7303063,
        longitude: -121.9537478
    },
    {
        locator_number: 232636,
        park_name: "Big Basin Redwoods State Park (Incl. Little Basin State Park and Rancho     del Oso)",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.0973052,
        longitude: -122.2743451
    },
    {
        locator_number: 232637,
        park_name: "Bodie State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.2133085,
        longitude: -119.015125
    },
    {
        locator_number: 232638,
        park_name: "Bolsa Chica State Beach",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.6955698,
        longitude: -118.0487973
    },
    {
        locator_number: 232639,
        park_name: "Border Field State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 32.5450305,
        longitude: -117.12247
    },
    {
        locator_number: 232640,
        park_name: "Bothe-Napa Valley State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5429637,
        longitude: -122.5374817
    },
    {
        locator_number: 232641,
        park_name: "Brannan Island State Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.11021019999999,
        longitude: -121.696818
    },
    {
        locator_number: 232642,
        park_name: "Burleigh H. Murray Ranch Park Property",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.4563488,
        longitude: -122.3818708
    },
    {
        locator_number: 232643,
        park_name: "Burton Creek State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.1867301,
        longitude: -120.1250758
    },
    {
        locator_number: 232644,
        park_name: "Butano State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.2127738,
        longitude: -122.3053427
    },
    {
        locator_number: 232645,
        park_name: "Butte City Project Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 39.4630392,
        longitude: -121.992457
    },
    {
        locator_number: 232646,
        park_name: "Calaveras Big Trees State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.27751779999999,
        longitude: -120.3092982
    },
    {
        locator_number: 232647,
        park_name: "California Citrus State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.8986111,
        longitude: -117.4257031
    },
    {
        locator_number: 232648,
        park_name: "California Indian Heritage Center Park Property",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5729871,
        longitude: -121.4715497
    },
    {
        locator_number: 232649,
        park_name: "California State Capitol",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5765882,
        longitude: -121.4932368
    },
    {
        locator_number: 232650,
        park_name: "California State Mining and Mineral Museum Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.46478580000001,
        longitude: -119.9481939
    },
    {
        locator_number: 232651,
        park_name: "California State Railroad Museum Point of Interest",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5849363,
        longitude: -121.5042998
    },
    {
        locator_number: 232652,
        park_name: "Cambria State Marine Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.58383639999999,
        longitude: -121.1214333
    },
    {
        locator_number: 232653,
        park_name: "Candlestick Point State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.7127107,
        longitude: -122.3815252
    },
    {
        locator_number: 232654,
        park_name: "Cardiff State Beach",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.0098231,
        longitude: -117.27963
    },
    {
        locator_number: 232655,
        park_name: "Carlsbad State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 33.1012834,
        longitude: -117.3185839
    },
    {
        locator_number: 232656,
        park_name: "Carmel River State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.5373847,
        longitude: -121.9279355
    },
    {
        locator_number: 232657,
        park_name: "Carnegie State Vehicular Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.63412,
        longitude: -121.5445395
    },
    {
        locator_number: 232658,
        park_name: "Carpinteria State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.3930467,
        longitude: -119.5242547
    },
    {
        locator_number: 232659,
        park_name: "Caspar Headlands State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.3626881,
        longitude: -123.8172286
    },
    {
        locator_number: 232660,
        park_name: "Caspar Headlands State Natural Reserve",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.3596362,
        longitude: -123.8218673
    },
    {
        locator_number: 232661,
        park_name: "Castaic Lake State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.557656,
        longitude: -118.5690586
    },
    {
        locator_number: 232662,
        park_name: "Castle Crags State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.1482103,
        longitude: -122.3213725
    },
    {
        locator_number: 232663,
        park_name: "Castle Rock State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.22982349999999,
        longitude: -122.1252175
    },
    {
        locator_number: 232664,
        park_name: "Caswell Memorial State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.693819,
        longitude: -121.1874767
    },
    {
        locator_number: 232665,
        park_name: "Cayucos State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.4475405,
        longitude: -120.9040141
    },
    {
        locator_number: 232666,
        park_name: "China Camp State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.0012549,
        longitude: -122.4910712
    },
    {
        locator_number: 232667,
        park_name: "Chino Hills State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.9179635,
        longitude: -117.7245244
    },
    {
        locator_number: 232668,
        park_name: "Chumash Painted Cave State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.5041853,
        longitude: -119.7876117
    },
    {
        locator_number: 232669,
        park_name: "Clay Pit State Vehicular Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.4828123,
        longitude: -121.6123438
    },
    {
        locator_number: 232670,
        park_name: "Clear Lake State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.01063119999999,
        longitude: -122.8139383
    },
    {
        locator_number: 232671,
        park_name: "Colonel Allensworth State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.8634736,
        longitude: -119.3898788
    },
    {
        locator_number: 232672,
        park_name: "Columbia State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.0341006,
        longitude: -120.4020446
    },
    {
        locator_number: 232673,
        park_name: "Colusa-Sacramento River State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.2179335,
        longitude: -122.0148504
    },
    {
        locator_number: 232674,
        park_name: "Corona del Mar State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.5931079,
        longitude: -117.877057
    },
    {
        locator_number: 232675,
        park_name: "Crystal Cove State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.5800786,
        longitude: -117.8050864
    },
    {
        locator_number: 232676,
        park_name: "Cuyamaca Rancho State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 32.9280287,
        longitude: -116.5678078
    },
    {
        locator_number: 232677,
        park_name: "D. L. Bliss State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.97789909999999,
        longitude: -120.1027489
    },
    {
        locator_number: 232678,
        park_name: "Del Norte Coast Redwoods State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.66809240000001,
        longitude: -124.1139454
    },
    {
        locator_number: 232679,
        park_name: "Delta Meadows Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.1102102,
        longitude: -121.6968182
    },
    {
        locator_number: 232680,
        park_name: "Dockweiler State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 33.93053039999999,
        longitude: -118.4356632
    },
    {
        locator_number: 232681,
        park_name: "Doheny State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.4631511,
        longitude: -117.6878769
    },
    {
        locator_number: 232682,
        park_name: "Donner Memorial State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.3159261,
        longitude: -120.239782
    },
    {
        locator_number: 232683,
        park_name: "Eastern Kern County Onyx Ranch State Vehicular Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.6902305,
        longitude: -118.220634
    },
    {
        locator_number: 232684,
        park_name: "Ed Z'berg Sugar Pine Point State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.059481,
        longitude: -120.122333
    },
    {
        locator_number: 232685,
        park_name: "El Capitán State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.4595891,
        longitude: -120.0245304
    },
    {
        locator_number: 232686,
        park_name: "El Presidio de Santa Barbara State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.4225894,
        longitude: -119.6988934
    },
    {
        locator_number: 232687,
        park_name: "Emerald Bay State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.9542445,
        longitude: -120.110414
    },
    {
        locator_number: 232688,
        park_name: "Emeryville Crescent State Marine Reserve",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.8370897,
        longitude: -122.3090256
    },
    {
        locator_number: 232689,
        park_name: "Emma Wood State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.2932299,
        longitude: -119.3398523
    },
    {
        locator_number: 232690,
        park_name: "Empire Mine State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.205952,
        longitude: -121.0438606
    },
    {
        locator_number: 232691,
        park_name: "Estero Bluffs State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 35.4493467,
        longitude: -120.9185706
    },
    {
        locator_number: 232692,
        park_name: "Folsom Lake State Recreation Area",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.77265149999999,
        longitude: -121.1085636
    },
    {
        locator_number: 232693,
        park_name: "Folsom Powerhouse State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.6805029,
        longitude: -121.1758423
    },
    {
        locator_number: 232694,
        park_name: "Fort Humboldt State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.7767796,
        longitude: -124.1886311
    },
    {
        locator_number: 232695,
        park_name: "Fort Ord Dunes State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.6569675,
        longitude: -121.8223929
    },
    {
        locator_number: 232696,
        park_name: "Fort Ross State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.516043,
        longitude: -123.2459718
    },
    {
        locator_number: 232697,
        park_name: "Fort Tejon State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.87446259999999,
        longitude: -118.8935176
    },
    {
        locator_number: 232698,
        park_name: "Franks Tract State Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.03357870000001,
        longitude: -121.6212963
    },
    {
        locator_number: 232699,
        park_name: "Fremont Peak State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.7619201,
        longitude: -121.5034543
    },
    {
        locator_number: 232700,
        park_name: "Garrapata State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.4679829,
        longitude: -121.9074861
    },
    {
        locator_number: 232701,
        park_name: "Gavoita State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.4733557,
        longitude: -120.229478
    },
    {
        locator_number: 232702,
        park_name: "George J. Hatfield State Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.356222,
        longitude: -120.9593082
    },
    {
        locator_number: 232703,
        park_name: "Governor's Mansion State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.5801086,
        longitude: -121.4848862
    },
    {
        locator_number: 232704,
        park_name: "Gray Whale Cove State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.5645993,
        longitude: -122.5139689
    },
    {
        locator_number: 232705,
        park_name: "Great Valley Grasslands State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.2810297,
        longitude: -120.8642492
    },
    {
        locator_number: 232706,
        park_name: "Greenwood State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.12676159999999,
        longitude: -123.7178921
    },
    {
        locator_number: 232707,
        park_name: "Grizzly Creek Redwood State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.4867464,
        longitude: -123.9050925
    },
    {
        locator_number: 232708,
        park_name: "Grover Hot Springs State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.6960394,
        longitude: -119.8438595
    },
    {
        locator_number: 232709,
        park_name: "Half Moon Bay State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.4760761,
        longitude: -122.4489731
    },
    {
        locator_number: 232710,
        park_name: "Harmony Headlands State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 35.477972,
        longitude: -120.9922687
    },
    {
        locator_number: 232711,
        park_name: "Harry A. Merlo State Recreation Area",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.1603148,
        longitude: -124.1195038
    },
    {
        locator_number: 232712,
        park_name: "Hatton Canyon Park Property",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.54385,
        longitude: -121.9066206
    },
    {
        locator_number: 232713,
        park_name: "Hearst San Simeon State Historical Monument",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.6852076,
        longitude: -121.1682251
    },
    {
        locator_number: 232714,
        park_name: "Hearst San Simeon State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.5926428,
        longitude: -121.1166162
    },
    {
        locator_number: 232715,
        park_name: "Heber Dunes State Vehicular Recreation Area",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 32.7179947,
        longitude: -115.391773
    },
    {
        locator_number: 232716,
        park_name: "Hendy Woods State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.06980149999999,
        longitude: -123.4709108
    },
    {
        locator_number: 232717,
        park_name: "Henry Cowell Redwoods State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.0535759,
        longitude: -122.0976205
    },
    {
        locator_number: 232718,
        park_name: "Henry W. Coe State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.1914002,
        longitude: -121.4359759
    },
    {
        locator_number: 232719,
        park_name: "Hollister Hills State Vehicular Recreation Area",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.7746599,
        longitude: -121.4250707
    },
    {
        locator_number: 232720,
        park_name: "Humboldt Lagoons State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: false,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.2250536,
        longitude: -124.0981292
    },
    {
        locator_number: 232721,
        park_name: "Humboldt Redwoods State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.3146515,
        longitude: -123.9776858
    },
    {
        locator_number: 232722,
        park_name: "Hungry Valley State Vehicular Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.79171150000001,
        longitude: -118.8715552
    },
    {
        locator_number: 232723,
        park_name: "Huntington State Beach",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.6380444,
        longitude: -117.9736122
    },
    {
        locator_number: 232724,
        park_name: "Indian Grinding Rock State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.425104,
        longitude: -120.6408647
    },
    {
        locator_number: 232725,
        park_name: "Indio Hills Palms Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 33.83725800000001,
        longitude: -116.3091264
    },
    {
        locator_number: 232726,
        park_name: "Jack London State Historic Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.35631710000001,
        longitude: -122.5417694
    },
    {
        locator_number: 232727,
        park_name: "Jedediah Smith Redwoods State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.7955087,
        longitude: -124.1046827
    },
    {
        locator_number: 232728,
        park_name: "John B. Dewitt Redwoods State Natural Reserve",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5370031,
        longitude: -123.0063252
    },
    {
        locator_number: 232729,
        park_name: "John Little State Natural Reserve",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.11933929999999,
        longitude: -121.6318751
    },
    {
        locator_number: 232730,
        park_name: "Jug Handle State Natural Reserve",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.37778009999999,
        longitude: -123.8136341
    },
    {
        locator_number: 232731,
        park_name: "Julia Pfeiffer Burns State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.1691714,
        longitude: -121.671498
    },
    {
        locator_number: 232732,
        park_name: "Kenneth Hahn State Recreation Area (incl. Baldwin Hills Scenic     Overlook)",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.0182,
        longitude: -118.3819125
    },
    {
        locator_number: 232733,
        park_name: "Kings Beach State Recreation Area",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.2366319,
        longitude: -120.0253758
    },
    {
        locator_number: 232734,
        park_name: "Kruse Rhododendron State Natural Reserve",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5931617,
        longitude: -123.3392695
    },
    {
        locator_number: 232735,
        park_name: "La Purísima Mission State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.66977,
        longitude: -120.420619
    },
    {
        locator_number: 232736,
        park_name: "Lake Del Valle State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.594493,
        longitude: -121.7089382
    },
    {
        locator_number: 232737,
        park_name: "Lake Oroville State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.535,
        longitude: -121.4669444
    },
    {
        locator_number: 232738,
        park_name: "Lake Perris State Recreation Area",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.8569506,
        longitude: -117.1764723
    },
    {
        locator_number: 232739,
        park_name: "Lake Valley State Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.871139,
        longitude: -120.007879
    },
    {
        locator_number: 232740,
        park_name: "Leland Stanford Mansion State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5761903,
        longitude: -121.4978549
    },
    {
        locator_number: 232741,
        park_name: "Leo Carrillo State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.0436171,
        longitude: -118.9358055
    },
    {
        locator_number: 232742,
        park_name: "Leucadia State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 33.0651901,
        longitude: -117.3047175
    },
    {
        locator_number: 232743,
        park_name: "Lighthouse Field State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.95339480000001,
        longitude: -122.0288273
    },
    {
        locator_number: 232744,
        park_name: "Limekiln State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.0112678,
        longitude: -121.5164712
    },
    {
        locator_number: 232745,
        park_name: "Little River State Beach",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.0161862,
        longitude: -124.1117836
    },
    {
        locator_number: 232746,
        park_name: "Locke Boarding House Museum Point of Interest",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.2512654,
        longitude: -121.510032
    },
    {
        locator_number: 232747,
        park_name: "Los Angeles State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.06868850000001,
        longitude: -118.231565
    },
    {
        locator_number: 232748,
        park_name: "Los Encinos State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.1603045,
        longitude: -118.4985806
    },
    {
        locator_number: 232749,
        park_name: "Los Osos Oaks State Natural Reserve",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 35.3062715,
        longitude: -120.8134694
    },
    {
        locator_number: 232750,
        park_name: "MacKerricher State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.4884502,
        longitude: -123.7878557
    },
    {
        locator_number: 232751,
        park_name: "Mailliard Redwoods State Natural Reserve",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.9047577,
        longitude: -123.3345856
    },
    {
        locator_number: 232752,
        park_name: "Malakoff Diggins State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.3707557,
        longitude: -120.8979645
    },
    {
        locator_number: 232753,
        park_name: "Malibu Creek State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.0643922,
        longitude: -118.6994433
    },
    {
        locator_number: 232754,
        park_name: "Malibu Lagoon State Beach (incl. Adamson House)",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.0345263,
        longitude: -118.680519
    },
    {
        locator_number: 232755,
        park_name: "Manchester State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.9813643,
        longitude: -123.6988439
    },
    {
        locator_number: 232756,
        park_name: "Mandalay State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.2011192,
        longitude: -119.248352
    },
    {
        locator_number: 232757,
        park_name: "Manresa State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.9321893,
        longitude: -121.8630067
    },
    {
        locator_number: 232758,
        park_name: "Marconi Conference Center State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.1442809,
        longitude: -122.8780043
    },
    {
        locator_number: 232759,
        park_name: "Marina State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.69634309999999,
        longitude: -121.8090743
    },
    {
        locator_number: 232760,
        park_name: "Marsh Creek State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.8900704,
        longitude: -121.7382277
    },
    {
        locator_number: 232761,
        park_name: "Marshall Gold Discovery State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.8000647,
        longitude: -120.8923429
    },
    {
        locator_number: 232762,
        park_name: "Martial Cottle Park State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.26330179999999,
        longitude: -121.8341303
    },
    {
        locator_number: 232763,
        park_name: "McArthur-Burney Falls Memorial State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.0124498,
        longitude: -121.6502456
    },
    {
        locator_number: 232764,
        park_name: "McConnell State Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.4158738,
        longitude: -120.7110885
    },
    {
        locator_number: 232765,
        park_name: "McGrath State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.221001,
        longitude: -119.2596809
    },
    {
        locator_number: 232766,
        park_name: "McLaughlin Eastshore State Park State Seashore",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.8680408,
        longitude: -122.3088705
    },
    {
        locator_number: 232767,
        park_name: "Mendocino Headlands State Park (incl. Ford House)",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.30897059999999,
        longitude: -123.8062341
    },
    {
        locator_number: 232768,
        park_name: "Mendocino Woodlands State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 39.338437,
        longitude: -123.6986763
    },
    {
        locator_number: 232769,
        park_name: "Millerton Lake State Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.0202397,
        longitude: -119.6964205
    },
    {
        locator_number: 232770,
        park_name: "Mono Lake Tufa State Natural Reserve",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.9787925,
        longitude: -119.132492
    },
    {
        locator_number: 232771,
        park_name: "Montaña de Oro State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: true,
        dog_in_campground: true,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 35.2723111,
        longitude: -120.8867814
    },
    {
        locator_number: 232772,
        park_name: "Montara State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.54688710000001,
        longitude: -122.5149481
    },
    {
        locator_number: 232773,
        park_name: "Monterey Bay Area State Beaches",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.6122612,
        longitude: -121.8579939
    },
    {
        locator_number: 232774,
        park_name: "Monterey State Beach",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.6122612,
        longitude: -121.8579939
    },
    {
        locator_number: 232775,
        park_name: "Monterey State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.5997388,
        longitude: -121.8936283
    },
    {
        locator_number: 232776,
        park_name: "Montgomery Woods State Natural Reserve",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 39.2290217,
        longitude: -123.3878855
    },
    {
        locator_number: 232777,
        park_name: "Moonlight State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 33.0478214,
        longitude: -117.2972948
    },
    {
        locator_number: 232778,
        park_name: "Morro Bay State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.35269350000001,
        longitude: -120.8392652
    },
    {
        locator_number: 232779,
        park_name: "Morro Strand State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 35.3918466,
        longitude: -120.8664024
    },
    {
        locator_number: 232780,
        park_name: "Moss Landing State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.81491,
        longitude: -121.7913048
    },
    {
        locator_number: 232781,
        park_name: "Mount Diablo State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.8808335,
        longitude: -121.9173287
    },
    {
        locator_number: 232782,
        park_name: "Mount San Jacinto State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.814463,
        longitude: -116.6791834
    },
    {
        locator_number: 232783,
        park_name: "Mount Tamalpais State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.9235439,
        longitude: -122.5964705
    },
    {
        locator_number: 232784,
        park_name: "Natural Bridges State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.9502805,
        longitude: -122.0575721
    },
    {
        locator_number: 232785,
        park_name: "Navarro River Redwoods State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.17678799999999,
        longitude: -123.6895911
    },
    {
        locator_number: 232786,
        park_name: "New Brighton State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.9784397,
        longitude: -121.9382294
    },
    {
        locator_number: 232787,
        park_name: "Oceano Dunes State Vehicular Recreation Area",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.1055739,
        longitude: -120.630317
    },
    {
        locator_number: 232788,
        park_name: "Ocotillo Wells State Vehicular Recreation Area",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.1559056,
        longitude: -116.1675902
    },
    {
        locator_number: 232789,
        park_name: "Old Sacramento State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.5843712,
        longitude: -121.5045324
    },
    {
        locator_number: 232790,
        park_name: "Old Town San Diego State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 32.7549063,
        longitude: -117.1976407
    },
    {
        locator_number: 232791,
        park_name: "Olompali State Historic Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.14962199999999,
        longitude: -122.5670438
    },
    {
        locator_number: 232792,
        park_name: "Pacheco State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.0650751,
        longitude: -121.2116388
    },
    {
        locator_number: 232793,
        park_name: "Pacifica State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.5988889,
        longitude: -122.5019444
    },
    {
        locator_number: 232794,
        park_name: "Palomar Mountain State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.3390844,
        longitude: -116.9067302
    },
    {
        locator_number: 232795,
        park_name: "Patricks' Point State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.1364671,
        longitude: -124.1552219
    },
    {
        locator_number: 232796,
        park_name: "Pelican State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.99253900000001,
        longitude: -124.2090521
    },
    {
        locator_number: 232797,
        park_name: "Pescadero State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.2621666,
        longitude: -122.4133085
    },
    {
        locator_number: 232798,
        park_name: "Petaluma Adobe State Historic Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.2564255,
        longitude: -122.5823606
    },
    {
        locator_number: 232799,
        park_name: "Pfeiffer Big Sur State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.2475861,
        longitude: -121.7790088
    },
    {
        locator_number: 232800,
        park_name: "Picacho State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.0080163,
        longitude: -114.6200472
    },
    {
        locator_number: 232801,
        park_name: "Pigeon Point Light Station State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.1820934,
        longitude: -122.393548
    },
    {
        locator_number: 232802,
        park_name: "Pío Pico State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.9936111,
        longitude: -118.0711111
    },
    {
        locator_number: 232803,
        park_name: "Pismo State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.1063844,
        longitude: -120.6269957
    },
    {
        locator_number: 232804,
        park_name: "Placerita Canyon State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.3779607,
        longitude: -118.4675271
    },
    {
        locator_number: 232805,
        park_name: "Plumas-Eureka State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.75694619999999,
        longitude: -120.6980299
    },
    {
        locator_number: 232806,
        park_name: "Point Cabrillo Light Station State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.350629,
        longitude: -123.814654
    },
    {
        locator_number: 232807,
        park_name: "Point Dume State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.0110923,
        longitude: -118.8165959
    },
    {
        locator_number: 232808,
        park_name: "Point Lobos Ranch Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.5148125,
        longitude: -121.9217108
    },
    {
        locator_number: 232809,
        park_name: "Point Lobos State Natural Reserve",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.51591279999999,
        longitude: -121.9382398
    },
    {
        locator_number: 232810,
        park_name: "Point Mugu State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.08556240000001,
        longitude: -119.060935
    },
    {
        locator_number: 232811,
        park_name: "Point Sal State Beach",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.9021013,
        longitude: -120.6552713
    },
    {
        locator_number: 232812,
        park_name: "Point Sur State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.30906259999999,
        longitude: -121.8932592
    },
    {
        locator_number: 232813,
        park_name: "Pomponio State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.29216590000001,
        longitude: -122.407197
    },
    {
        locator_number: 232814,
        park_name: "Portola Redwoods State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.26213719999999,
        longitude: -122.2123153
    },
    {
        locator_number: 232815,
        park_name: "Prairie City State Vehicular Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.60130220000001,
        longitude: -121.1650757
    },
    {
        locator_number: 232816,
        park_name: "Prairie Creek Redwoods State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.4016041,
        longitude: -124.0416172
    },
    {
        locator_number: 232817,
        park_name: "Providence Mountains State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.94363209999999,
        longitude: -115.5136065
    },
    {
        locator_number: 232818,
        park_name: "Railtown 1897 State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.9509246,
        longitude: -120.4175469
    },
    {
        locator_number: 232819,
        park_name: "Rancho San Andres Castro Adobe Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.947273,
        longitude: -121.811407
    },
    {
        locator_number: 232820,
        park_name: "Red Rock Canyon State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.1058199,
        longitude: -118.6374615
    },
    {
        locator_number: 232821,
        park_name: "Refugio State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.4631659,
        longitude: -120.0701354
    },
    {
        locator_number: 232822,
        park_name: "Reynolds Wayside Campground",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.9438088,
        longitude: -123.7798151
    },
    {
        locator_number: 232823,
        park_name: "Richardson Grove State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.01925689999999,
        longitude: -123.7925147
    },
    {
        locator_number: 232824,
        park_name: "Rio de Los Angeles State Park State Recreation Area",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.098711,
        longitude: -118.2358502
    },
    {
        locator_number: 232825,
        park_name: "Robert H. Meyer Memorial State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.0383786,
        longitude: -118.8753501
    },
    {
        locator_number: 232826,
        park_name: "Robert Louis Stevenson State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.6616875,
        longitude: -122.6217555
    },
    {
        locator_number: 232827,
        park_name: "Robert W. Crown Memorial State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.7661819,
        longitude: -122.2719691
    },
    {
        locator_number: 232828,
        park_name: "Russian Gulch State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.33252570000001,
        longitude: -123.8061091
    },
    {
        locator_number: 232829,
        park_name: "Saddleback Butte State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.6758215,
        longitude: -117.7989521
    },
    {
        locator_number: 232830,
        park_name: "Salinas River State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.77536509999999,
        longitude: -121.7946568
    },
    {
        locator_number: 232831,
        park_name: "Salt Point State Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.57648470000001,
        longitude: -123.3317814
    },
    {
        locator_number: 232832,
        park_name: "Salton Sea State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.5088385,
        longitude: -115.9181159
    },
    {
        locator_number: 232833,
        park_name: "Samuel P. Taylor State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.0242949,
        longitude: -122.7213981
    },
    {
        locator_number: 232834,
        park_name: "San Bruno Mountain State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.6968729,
        longitude: -122.4339347
    },
    {
        locator_number: 232835,
        park_name: "San Buenaventura State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.2697414,
        longitude: -119.2770569
    },
    {
        locator_number: 232836,
        park_name: "San Clemente State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.4043306,
        longitude: -117.6028514
    },
    {
        locator_number: 232837,
        park_name: "San Elijo State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.0214987,
        longitude: -117.2842602
    },
    {
        locator_number: 232838,
        park_name: "San Gregorio State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.3229987,
        longitude: -122.4033078
    },
    {
        locator_number: 232839,
        park_name: "San Juan Bautista State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.84455670000001,
        longitude: -121.5347776
    },
    {
        locator_number: 232840,
        park_name: "San Luis Reservoir State Recreation Area",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.0797973,
        longitude: -121.0982009
    },
    {
        locator_number: 232841,
        park_name: "San Onofre State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.3728077,
        longitude: -117.5656012
    },
    {
        locator_number: 232842,
        park_name: "San Pasqual Battlefield State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 33.0884334,
        longitude: -116.9828546
    },
    {
        locator_number: 232843,
        park_name: "San Timoteo Canyon Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.03001469999999,
        longitude: -117.204761
    },
    {
        locator_number: 232844,
        park_name: "Santa Cruz Mission State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.977564,
        longitude: -122.0280123
    },
    {
        locator_number: 232845,
        park_name: "Santa Monica State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.0129033,
        longitude: -118.5017237
    },
    {
        locator_number: 232846,
        park_name: "Santa Susana Pass State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.2637283,
        longitude: -118.6325517
    },
    {
        locator_number: 232847,
        park_name: "Schooner Gulch State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.868155,
        longitude: -123.6546397
    },
    {
        locator_number: 232848,
        park_name: "Seacliff State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.971997,
        longitude: -121.9139256
    },
    {
        locator_number: 232849,
        park_name: "Shasta State Historic Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.5992482,
        longitude: -122.4917724
    },
    {
        locator_number: 232850,
        park_name: "Silver Strand State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.1506785,
        longitude: -119.2197283
    },
    {
        locator_number: 232851,
        park_name: "Silverwood Lake State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.2857189,
        longitude: -117.3525307
    },
    {
        locator_number: 232852,
        park_name: "Sinkyone Wilderness State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.9202867,
        longitude: -123.9396803
    },
    {
        locator_number: 232853,
        park_name: "Smithe Redwoods State Natural Reserve",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.902685,
        longitude: -123.7513714
    },
    {
        locator_number: 232854,
        park_name: "Sonoma Coast State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: false,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.42421090000001,
        longitude: -123.1011733
    },
    {
        locator_number: 232855,
        park_name: "Sonoma State Historic Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.29383329999999,
        longitude: -122.4569229
    },
    {
        locator_number: 232856,
        park_name: "South Carlsbad State Beach",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.1026212,
        longitude: -117.320145
    },
    {
        locator_number: 232857,
        park_name: "South Yuba River State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: true,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.2927268,
        longitude: -121.1935665
    },
    {
        locator_number: 232858,
        park_name: "Standish-Hickey State Recreation Area",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.8774712,
        longitude: -123.7375985
    },
    {
        locator_number: 232859,
        park_name: "State Indian Museum State Historic Park",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.649594,
        longitude: -117.847417
    },
    {
        locator_number: 232860,
        park_name: "Stone Lake Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 38.3709578,
        longitude: -121.4955272
    },
    {
        locator_number: 232861,
        park_name: "Sugarloaf Ridge State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.4371892,
        longitude: -122.51629
    },
    {
        locator_number: 232862,
        park_name: "Sunset State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.8867526,
        longitude: -121.8325358
    },
    {
        locator_number: 232863,
        park_name: "Sutter Buttes State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 39.20569999999999,
        longitude: -121.8202
    },
    {
        locator_number: 232864,
        park_name: "Sutter's Fort State Historic Park",
        dog_on_road: true,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.57233889999999,
        longitude: -121.4712056
    },
    {
        locator_number: 232865,
        park_name: "Tahoe State Recreation Area",
        dog_on_road: true,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.17533549999999,
        longitude: -120.1361955
    },
    {
        locator_number: 232866,
        park_name: "The Forest of Nisene Marks State Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.0175202,
        longitude: -121.905347
    },
    {
        locator_number: 232867,
        park_name: "Thornton State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.6980773,
        longitude: -122.4960046
    },
    {
        locator_number: 232868,
        park_name: "Tijuana Estuary NP Point of Interest",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 32.5513045,
        longitude: -117.114509
    },
    {
        locator_number: 232869,
        park_name: "Tolowa Dunes State Park",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.870055,
        longitude: -124.2036245
    },
    {
        locator_number: 232870,
        park_name: "Tomales Bay State Park",
        dog_on_road: true,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.123351,
        longitude: -122.9012578
    },
    {
        locator_number: 232871,
        park_name: "Tomo-Kahni State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 35.14825769999999,
        longitude: -118.3359672
    },
    {
        locator_number: 232872,
        park_name: "Topanga State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.0931823,
        longitude: -118.5873146
    },
    {
        locator_number: 232873,
        park_name: "Torrey Pines State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 32.9371818,
        longitude: -117.2616585
    },
    {
        locator_number: 232874,
        park_name: "Torrey Pines State Natural Reserve",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 32.9268576,
        longitude: -117.2593912
    },
    {
        locator_number: 232875,
        park_name: "Trinidad State Beach",
        dog_on_road: null,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 41.065402,
        longitude: -124.1503472
    },
    {
        locator_number: 232876,
        park_name: "Trione-Annadel State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.43294059999999,
        longitude: -122.6324134
    },
    {
        locator_number: 232877,
        park_name: "Tule Elk State Natural Reserve",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 35.32214619999999,
        longitude: -119.3640088
    },
    {
        locator_number: 232878,
        park_name: "Turlock Lake State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 37.6258955,
        longitude: -120.5909176
    },
    {
        locator_number: 232879,
        park_name: "Twin Lakes State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 36.9623,
        longitude: -121.997725
    },
    {
        locator_number: 232880,
        park_name: "Van Damme State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: true,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.2757228,
        longitude: -123.7642849
    },
    {
        locator_number: 232881,
        park_name: "Verdugo Mountains Park Property",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.2273665,
        longitude: -118.3276462
    },
    {
        locator_number: 232882,
        park_name: "Ward Creek Park Property",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.1324046,
        longitude: -120.1580162
    },
    {
        locator_number: 232883,
        park_name: "Washoe Meadows State Park",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.8766009,
        longitude: -120.0292602
    },
    {
        locator_number: 232884,
        park_name: "Wassama Round House State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 37.3746312,
        longitude: -119.7209814
    },
    {
        locator_number: 232885,
        park_name: "Watts Towers of Simon Rodia State Historic Park",
        dog_on_road: true,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 33.9388619,
        longitude: -118.2416196
    },
    {
        locator_number: 232886,
        park_name: "Weaverville Joss House State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.7318175,
        longitude: -122.940522
    },
    {
        locator_number: 232887,
        park_name: "Westport-Union Landing State Beach",
        dog_on_road: null,
        dog_on_trail: null,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.677064,
        longitude: -123.7912254
    },
    {
        locator_number: 232888,
        park_name: "Wilder Ranch State Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.9608175,
        longitude: -122.0833662
    },
    {
        locator_number: 232889,
        park_name: "Wildwood Canyon Park Property",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.20271040000001,
        longitude: -118.2983857
    },
    {
        locator_number: 232890,
        park_name: "Will Rogers State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 34.03543059999999,
        longitude: -118.5367041
    },
    {
        locator_number: 232891,
        park_name: "Will Rogers State Historic Park",
        dog_on_road: true,
        dog_on_trail: true,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 34.0549876,
        longitude: -118.5125758
    },
    {
        locator_number: 232892,
        park_name: "William B. Ide Adobe State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 40.196773,
        longitude: -122.225351
    },
    {
        locator_number: 232893,
        park_name: "Woodland Opera House State Historic Park",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: null,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 38.6779007,
        longitude: -121.7720943
    },
    {
        locator_number: 232894,
        park_name: "Woodson Bridge State Recreation Area",
        dog_on_road: true,
        dog_on_trail: false,
        dog_on_beach: null,
        dog_in_campground: true,
        pet_friendly_rating: null,
        area_overall_rating: null,
        latitude: 39.9151405,
        longitude: -122.0851666
    },
    {
        locator_number: 232895,
        park_name: "Zmudowski State Beach",
        dog_on_road: false,
        dog_on_trail: false,
        dog_on_beach: false,
        dog_in_campground: false,
        pet_friendly_rating: 0,
        area_overall_rating: null,
        latitude: 36.8426469,
        longitude: -121.8048278
    }
];